//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biblioteca
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> usuario_id { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
